const lightColors = {
    primary: '#3355DB',
    ascent: '#02BBBB',
    success: '#08EC08',
    successBackground: '#BBFFBB',
    light: '#A49D9D',
    error: '#B7201D',
    errorBackground: '#FFAAAA',
    info: '#7B8434',
    cardBackground: '#FFFFFF',
    primaryText: '#000000',
    selectionColor: '#11229922',
    inversePrimaryText: '#ffffff',
    secondaryText: '#646262',
    inverseSecondaryText: '#ABAFB1',
    secondaryDarkText: '#3f3f3f',
    secondaryLightText: '#969696',
    pageBackground: '#ECECEC',
    inverseBackground: '#273037',
    separator: '#bebebe',
    badgeColor: '#e63729E5',
    badgeTextColor: '#FFFFFF',
    highlight: '#A7970FDD',
    editBoxBackGround: '#EBF0EB',
    placeholderColor: '#B1B1B1',
    cardSeparator: '#D7770F',
    secondaryBackground: '#f5f5f5',
    disableItem: '#C0C0C0',
    surfaceView: '#00000099',
  };
  
  export const Colors = lightColors;